[workspace.package]
name = "substrate-bank"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
	"pallets/pallet-bank",
	"pallets/pallet-template",
	"pallets/pallet-roles",
	"primitives",
	"traits",
]