[workspace]
members = [
    "node",
    "pallets/pallet-template",
    "pallets/pallet-roles",
    "pallets/pallet-bank",
	"primitives",
	"traits",
    "runtime",
]
resolver = "2"
[profile.release]
panic = "unwind"
