[alias]
xy-test = "test --lib --features runtime-benchmarks,try-runtime"

xy-clippy = "clippy --all-targets --features runtime-benchmarks,try-runtime -- -D warnings"

xy-build = "build --release --features runtime-benchmarks,try-runtime"



