
//! Autogenerated weights for pallet_nft
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-04-03, STEPS: `20`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Xiaos-MacBook-Pro.local`, CPU: `<UNKNOWN>`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 1024

// Executed Command:
// ./target/release/xy-chain
// benchmark
// pallet
// --extrinsic
// *
// --pallet
// pallet_nft
// --output
// ./pallets/pallet-nft/src/weights.rs
// --steps=20
// --repeat=20
// --template=weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_nft.
pub trait WeightInfo {
	fn request_mint() -> Weight;
	fn burned() -> Weight;
	fn transfer() -> Weight;
	fn approve_nft() -> Weight;
	fn force_burn() -> Weight;
}

/// Weights for pallet_nft using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Roles::AccountRoles` (r:1 w:0)
	/// Proof: `Roles::AccountRoles` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Nft::NextNftId` (r:1 w:1)
	/// Proof: `Nft::NextNftId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Nft::PendingNft` (r:0 w:1)
	/// Proof: `Nft::PendingNft` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn request_mint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `292`
		//  Estimated: `3514`
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(16_000_000, 3514)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Nft::Nfts` (r:1 w:1)
	/// Proof: `Nft::Nfts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Nft::Owners` (r:1 w:1)
	/// Proof: `Nft::Owners` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn burned() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `208`
		//  Estimated: `3673`
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(16_000_000, 3673)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Nft::Nfts` (r:1 w:0)
	/// Proof: `Nft::Nfts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Nft::Owners` (r:1 w:1)
	/// Proof: `Nft::Owners` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Roles::AccountRoles` (r:1 w:0)
	/// Proof: `Roles::AccountRoles` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `442`
		//  Estimated: `3907`
		// Minimum execution time: 20_000_000 picoseconds.
		Weight::from_parts(20_000_000, 3907)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Roles::AccountRoles` (r:1 w:0)
	/// Proof: `Roles::AccountRoles` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Nft::PendingNft` (r:1 w:1)
	/// Proof: `Nft::PendingNft` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Nft::Owners` (r:0 w:1)
	/// Proof: `Nft::Owners` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Nft::Nfts` (r:0 w:1)
	/// Proof: `Nft::Nfts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn approve_nft() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `421`
		//  Estimated: `3886`
		// Minimum execution time: 23_000_000 picoseconds.
		Weight::from_parts(23_000_000, 3886)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Nft::Owners` (r:1 w:1)
	/// Proof: `Nft::Owners` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Nft::Nfts` (r:0 w:1)
	/// Proof: `Nft::Nfts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn force_burn() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `188`
		//  Estimated: `3653`
		// Minimum execution time: 11_000_000 picoseconds.
		Weight::from_parts(11_000_000, 3653)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: `Roles::AccountRoles` (r:1 w:0)
	/// Proof: `Roles::AccountRoles` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Nft::NextNftId` (r:1 w:1)
	/// Proof: `Nft::NextNftId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Nft::PendingNft` (r:0 w:1)
	/// Proof: `Nft::PendingNft` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn request_mint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `292`
		//  Estimated: `3514`
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(16_000_000, 3514)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Nft::Nfts` (r:1 w:1)
	/// Proof: `Nft::Nfts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Nft::Owners` (r:1 w:1)
	/// Proof: `Nft::Owners` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn burned() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `208`
		//  Estimated: `3673`
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(16_000_000, 3673)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Nft::Nfts` (r:1 w:0)
	/// Proof: `Nft::Nfts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Nft::Owners` (r:1 w:1)
	/// Proof: `Nft::Owners` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Roles::AccountRoles` (r:1 w:0)
	/// Proof: `Roles::AccountRoles` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `442`
		//  Estimated: `3907`
		// Minimum execution time: 20_000_000 picoseconds.
		Weight::from_parts(20_000_000, 3907)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Roles::AccountRoles` (r:1 w:0)
	/// Proof: `Roles::AccountRoles` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Nft::PendingNft` (r:1 w:1)
	/// Proof: `Nft::PendingNft` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Nft::Owners` (r:0 w:1)
	/// Proof: `Nft::Owners` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Nft::Nfts` (r:0 w:1)
	/// Proof: `Nft::Nfts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn approve_nft() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `421`
		//  Estimated: `3886`
		// Minimum execution time: 23_000_000 picoseconds.
		Weight::from_parts(23_000_000, 3886)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Nft::Owners` (r:1 w:1)
	/// Proof: `Nft::Owners` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Nft::Nfts` (r:0 w:1)
	/// Proof: `Nft::Nfts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn force_burn() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `188`
		//  Estimated: `3653`
		// Minimum execution time: 11_000_000 picoseconds.
		Weight::from_parts(11_000_000, 3653)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}
